spring:
  application:
    name: orders
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/orders?createDatabaseIfNotExist=true
    username: root
    password: 4149
  jpa:
    show-sql: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/

server:
  port: 0